# Generated by Django 3.0.1 on 2021-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210801_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='loan',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
