# Generated by Django 3.0.1 on 2021-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210801_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
