# Generated by Django 3.0.1 on 2021-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210808_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to=''),
        ),
    ]
