# Generated by Django 3.0.1 on 2021-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210808_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='tags',
        ),
        migrations.AddField(
            model_name='customer',
            name='accommodation_status',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Renting', 'Renting')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='alternative_source_of_income',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Self employed', 'Self employed'), ('None', 'No Source of income')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='annual_or_season_turnover',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='arable_land_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='average_monthly_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='average_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='dedication',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='drainage',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='drought_frequencies_in_past_10_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='education_level',
            field=models.CharField(choices=[('Graduated', 'Graduated'), ('A level', 'A level'), ('O level', 'O level'), ('Primary level', 'Primary level')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='experience_in_farming',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='farm_assets',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='floods_frequencies_in_past_10_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='household_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='land_tenure',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Renting', 'Renting')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='moisture_levels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='most_recent_annual_or_season_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='nitrogen_Levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='pest_and_diseases_frequency',
            field=models.CharField(choices=[('Low', 'Low'), ('Mild', 'Mild'), ('Severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='potassium_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='soil_type',
            field=models.CharField(choices=[('Clay', 'Clay'), ('Loom', 'Loom'), ('Sand', 'Sand')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_current_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='utilised_land_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='water_content',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
